### ISSUE TITLE
部署后点击精选模板报错了

### ISSUE THREAD

**Issue by karlxu11** [zxhm001/DataDraw#2]
[ 2019-04-16T13:51:18+08:00 ] 127.0.0.1 GET 127.0.0.1/template
[ sql ] [ DB ] CONNECT:[ UseTime:0.002000s ] mysql:host=127.0.0.1;port=3306;dbname=lite;charset=utf8
[ sql ] [ SQL ] SHOW COLUMNS FROM `sd_users` [ RunTime:0.012000s ]
[ sql ] [ SQL ] SELECT * FROM `sd_users` WHERE  `id` = 2  AND `user_status` = 0 LIMIT 1 [ RunTime:0.001000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `sd_groups` [ RunTime:0.012000s ]
[ sql ] [ SQL ] SELECT * FROM `sd_groups` WHERE  `id` = 3 LIMIT 1 [ RunTime:0.000000s ]
[ sql ] [ SQL ] SHOW COLUMNS FROM `sd_policy` [ RunTime:0.011000s ]
[ sql ] [ SQL ] SELECT * FROM `sd_policy` WHERE  `id` = 1 LIMIT 1 [ RunTime:0.001000s ]
[ error ] [10501]SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lite.sd_template_class' doesn't exist

数据库少了张表？

**Comment by zxhm001** [comment]
模板数据单独导出了，在文档说明配置数据库部分有专门说明，你可能看漏了

**Comment by karlxu11** [comment]
> 模板数据单独导出了，在文档说明配置数据库部分有专门说明，你可能看漏了

感谢回复，确实看漏了，谢谢提醒！
