### ISSUE TITLE
请问保存画图后在首页的缩略图没有了，应该怎么设置？

### ISSUE THREAD

**Issue by karlxu11** [zxhm001/DataDraw#4]
![image](https://user-images.githubusercontent.com/7956041/57744417-b100cf80-76fb-11e9-8aa1-f162c70ee7d4.png)

**Comment by zxhm001** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7956041/57744417-b100cf80-76fb-11e9-8aa1-f162c70ee7d4.png)

你是用的哪个版本来着，如果是[更新可以使用Cloudreve配置的云服务器 ](https://github.com/zxhm001/DataDraw/commit/aba17da3b6f6c4e841f8a3e3061e03a20a4809f4)这个更新之后，使用本地存储策略，就会出现这样的情况，后来有更新[修复改进图片机制时本地策略BUG ](https://github.com/zxhm001/DataDraw/commit/b9ad1b260274314d63469d52020c7163aaa0b15f)

**Comment by zxhm001** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7956041/57744417-b100cf80-76fb-11e9-8aa1-f162c70ee7d4.png)

或者你是用的我的网站？那清空一下浏览器缓存，刷新就可以啦

**Comment by karlxu11** [comment]
我用的是上个月16号的，在本地部署后没问题，本地用xampp，然后把整个打包传到服务器上就没有缩略图了。目前本地是有缩略图的。

**Comment by zxhm001** [comment]
> 
> 
> 我用的是上个月16号的，在本地部署后没问题，本地用xampp，然后把整个打包传到服务器上就没有缩略图了。目前本地是有缩略图的。

你的数据库是咋部署的来着。。。之前为了支持各种存储策略缩略图是保存在数据库里的

**Comment by karlxu11** [comment]
数据库我把根目录下的mysql.sql导入了，然后把templates里的sql也导入了，逻辑代码一点都没动，因为不太熟PHP

**Comment by karlxu11** [comment]
![image](https://user-images.githubusercontent.com/7956041/57820238-757b0980-77be-11e9-824d-4619a0561e78.png)
是保存在这个表里吧

**Comment by zxhm001** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/7956041/57820238-757b0980-77be-11e9-824d-4619a0561e78.png)
> 是保存在这个表里吧

是呀，看起来这个表是有数据的。。其实如果没有数据也不应该是你那边展示的那个情况，应该展示个xml图标来着。。。

**Comment by karlxu11** [comment]
我修改了File里的XmlThumb，直接$this->redirect('/static/img/text-xml.png');
目前不展示缩略图也OK

**Comment by zxhm001** [comment]
这个问题我找到答案了。。你是用的IE浏览器或者IE的内核吗？

**Comment by zxhm001** [comment]
这个问题我应该找到答案了。。你是用的IE浏览器或者IE的内核吗？

**Comment by karlxu11** [comment]
不是，主要是Chrome，后来我试了Firefox，IE 11 也不行

**Comment by zxhm001** [comment]
好吧。。我最近发现IE会把URL里的UTF8字符转换成乱码，看来也不是你出现那个问题的原因了
