### ISSUE TITLE
IE11无法新建图表

### ISSUE THREAD

**Issue by karlxu11** [zxhm001/DataDraw#5]
点击右上角的加号，然后输入图表名称，点击创建页面无反应，F12后见下图报错：
![image](https://user-images.githubusercontent.com/7956041/58218280-fdba5b00-7d38-11e9-8dd3-b2598f48e7a4.png)

**Comment by karlxu11** [comment]
这个是使用https://www.myshuju.net/Home在线版本的。

**Comment by zxhm001** [comment]
IE一直不支持File对象构造函数，好在微软已经放弃IE这个产品了，我也就没准备支持了

**Comment by karlxu11** [comment]
好的，感谢回复！
