### ISSUE TITLE
请问“图表创建错误”是什么问题？

### ISSUE THREAD

**Issue by ciddiaz** [zxhm001/DataDraw#7]
您好，今天发现无论用什么样的文件名创建新图表都提示“图表创建错误”，是服务器的问题吗？
![Snipaste_2019-11-19_15-51-29](https://user-images.githubusercontent.com/45554715/69127271-f0620b80-0ae4-11ea-9869-ee9db3a1173b.jpg)

**Comment by zxhm001** [comment]
SSL证书到期了导致的，刚刚已经重新部署了，现在好了
