### ISSUE TITLE
图示显示空空如也

### ISSUE THREAD

**Issue by ciddiaz** [zxhm001/DataDraw#8]
您好，绘制的部分图示有时候在文件夹中能正常显示缩略图，也能右键下载XML文件；但是一点开画布上就什么都没有，点输出PNG也是宽度0高度0；目前的解决办法是下载XML然后把代码贴到画图界面的“其它-编辑图表”里面去替换。请问有办法解决这一问题吗？

**Comment by zxhm001** [comment]
方便给xml发给我一下嘛，邮箱zxhm001@126.com

**Comment by zxhm001** [comment]
我看了下你给的文件，文件内容没啥问题，如果文件名也是你给我的文件名的话，应该就是文件名空格导致的，七牛云的文件在处理空格的时候用了下划线，然而上传回调结果竟然没有下划线，我这边也没做处理

**Comment by ciddiaz** [comment]
确实如此，以后创建新图表要注意文件名里不能带空格了
目前修复办法就是新建一个不带空格的图表然后把代码贴进去，直接删文件名空格也是不行的
